palette = 0 = #{{ surface.hex }}
palette = 1 = #{{ error.hex }}
palette = 2 = #{{ primary.hex }}
palette = 3 = #{{ tertiary.hex }}
palette = 4 = #{{ secondary.hex }}
palette = 5 = #{{ primary.hex }}
palette = 6 = #{{ tertiary.hex }}
palette = 7 = #{{ onSurface.hex }}
palette = 8 = #{{ onSurfaceVariant.hex }}
palette = 9 = #{{ errorContainer.hex }}
palette = 10 = #{{ primaryContainer.hex }}
palette = 11 = #{{ tertiaryContainer.hex }}
palette = 12 = #{{ secondaryContainer.hex }}
palette = 13 = #{{ primaryContainer.hex }}
palette = 14 = #{{ tertiaryContainer.hex }}
palette = 15 = #{{ surfaceBright.hex }}

background = #{{ surface.hex }}
foreground = #{{ onSurface.hex }}
cursor-color = #{{ onSurface.hex }}
cursor-text = #{{ surface.hex }}
selection-background = #{{ primaryContainer.hex }}
selection-foreground = #{{ onPrimaryContainer.hex }}