color0  #{{ surface.hex }}
color1  #{{ error.hex }}
color2  #{{ primary.hex }}
color3  #{{ tertiary.hex }}
color4  #{{ secondary.hex }}
color5  #{{ primary.hex }}
color6  #{{ tertiary.hex }}
color7  #{{ onSurface.hex }}
color8  #{{ onSurfaceVariant.hex }}
color9  #{{ errorContainer.hex }}
color10 #{{ primaryContainer.hex }}
color11 #{{ tertiaryContainer.hex }}
color12 #{{ secondaryContainer.hex }}
color13 #{{ primaryContainer.hex }}
color14 #{{ tertiaryContainer.hex }}
color15 #{{ surfaceBright.hex }}
cursor                  #{{ onSurface.hex }}
cursor_text_color       #{{ surface.hex }}
cursor_trail_color      #{{ onSurfaceVariant.hex }}
selection_foreground    #{{ onPrimaryContainer.hex }}
selection_background    #{{ primaryContainer.hex }}
background              #{{ surface.hex }}
foreground              #{{ onSurface.hex }}
url_color               #{{ primary.hex }}
active_border_color     #{{ primary.hex }}
inactive_border_color   #{{ outlineVariant.hex }}
bell_border_color       #{{ error.hex }}
active_tab_foreground   #{{ onPrimary.hex }}
active_tab_background   #{{ primary.hex }}
inactive_tab_foreground #{{ onSurfaceVariant.hex }}
inactive_tab_background #{{ surfaceContainer.hex }}
tab_bar_background      #{{ surfaceContainerLow.hex }}
tab_bar_margin_color    #{{ surfaceContainerLow.hex }}
mark1_foreground        #{{ onPrimary.hex }}
mark1_background        #{{ primary.hex }}
mark2_foreground        #{{ onSecondary.hex }}
mark2_background        #{{ secondary.hex }}
mark3_foreground        #{{ onTertiary.hex }}
mark3_background        #{{ tertiary.hex }}
scrollbar_handle_color  #{{ primary.hex }}