[bar.default]
background_opacity = 0.88999998010694981
capsule_fill = "surface"
capsule_foreground = "primary"
end = [
  "temp",
  "ram",
  "cpu",
  "tray",
  "volume",
  "wallpaper",
  "notifications",
  "control-center",
]
margin_edge = 0
margin_ends = 0
margin_opposite_edge = 1
radius = 0
start = ["workspaces", "media", "audio_visualizer"]

[widget.clock]
format = "{:%H:%M:%S}"

[widget.control-center]
custom_image = "/home/feltfomo/Downloads/nixos-customized.svg"
custom_image_colorize = true
scale = 1.1500000000000001

[widget.volume]
show_label = false

[widget.workspaces]
anchor = true
capsule = true
capsule_opacity = 0.0
capsule_padding = 0
capsule_radius = 0
focused_output_only = true
hide_when_empty = true
