[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = ["lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1"]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
box_height = 196.0
box_width = 810.0
cx = 1280.0
cy = 1317.0
output = "DP-1"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
center_password_text = false
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
box_height = 196.0
box_width = 810.0
cx = 1280.0
cy = 1317.0
output = "DP-2"
placement_height = 1440.0
placement_width = 2560.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
center_password_text = false
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true
