[theme]
source = "wallpaper"

[theme.templates]
builtin_ids = ["alacritty", "btop", "cava", "emacs", "foot", "gtk3", "gtk4", "helix", "kcolorscheme", "qt", "wezterm"]
community_ids = ["zed", "discord", "steam", "telegram"]
