[theme]
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[theme.templates]
# these remain built in because program does not own their templates yet
builtin_ids = ["alacritty", "emacs", "foot", "kcolorscheme", "qt", "wezterm"]
community_ids = ["zed", "discord", "steam", "telegram"]
