[wallpaper]
directory = "/home/feltfomo/Wallpapers"
transition_on_startup = true

[wallpaper.default]
path = "/home/feltfomo/Wallpapers/Pictures/wallhaven-8522py_2560x1440.png"

[wallpaper.last]
path = "/home/feltfomo/Wallpapers/Pictures/wallhaven-8522py_2560x1440.png"

[wallpaper.monitors.DP-1]
path = "/home/feltfomo/Wallpapers/Pictures/wallhaven-8522py_2560x1440.png"

[wallpaper.monitors.DP-2]
path = "/home/feltfomo/Wallpapers/Pictures/wallhaven-8522py_2560x1440.png"
