return {
	bg = "#{{ background.hex }}",
	bg_dim = "#{{ surfaceDim.hex }}",
	surface = "#{{ surface.hex }}",
	container = "#{{ surfaceContainer.hex }}",
	container_high = "#{{ surfaceContainerHigh.hex }}",
	container_highest = "#{{ surfaceContainerHighest.hex }}",
	fg = "#{{ onSurface.hex }}",
	fg_muted = "#{{ onSurfaceVariant.hex }}",
	primary = "#{{ primary.hex }}",
	on_primary = "#{{ onPrimary.hex }}",
	primary_container = "#{{ primaryContainer.hex }}",
	on_primary_container = "#{{ onPrimaryContainer.hex }}",
	secondary = "#{{ secondary.hex }}",
	secondary_container = "#{{ secondaryContainer.hex }}",
	on_secondary_container = "#{{ onSecondaryContainer.hex }}",
	tertiary = "#{{ tertiary.hex }}",
	on_tertiary = "#{{ onTertiary.hex }}",
	tertiary_container = "#{{ tertiaryContainer.hex }}",
	on_tertiary_container = "#{{ onTertiaryContainer.hex }}",
	error = "#{{ error.hex }}",
	error_container = "#{{ errorContainer.hex }}",
	on_error_container = "#{{ onErrorContainer.hex }}",
	outline = "#{{ outline.hex }}",
	outline_variant = "#{{ outlineVariant.hex }}",
	green = "#{{ term2.hex }}",
	yellow = "#{{ term3.hex }}",
	term = {
		"#{{ term0.hex }}",
		"#{{ term1.hex }}",
		"#{{ term2.hex }}",
		"#{{ term3.hex }}",
		"#{{ term4.hex }}",
		"#{{ term5.hex }}",
		"#{{ term6.hex }}",
		"#{{ term7.hex }}",
		"#{{ term8.hex }}",
		"#{{ term9.hex }}",
		"#{{ term10.hex }}",
		"#{{ term11.hex }}",
		"#{{ term12.hex }}",
		"#{{ term13.hex }}",
		"#{{ term14.hex }}",
		"#{{ term15.hex }}",
	},
}
