local dark = {
	bg = "{{ colors.background.dark.hex }}",
	bg_dim = "{{ colors.surface_dim.dark.hex }}",
	surface = "{{ colors.surface.dark.hex }}",
	container = "{{ colors.surface_container.dark.hex }}",
	container_high = "{{ colors.surface_container_high.dark.hex }}",
	container_highest = "{{ colors.surface_container_highest.dark.hex }}",
	fg = "{{ colors.on_surface.dark.hex }}",
	fg_muted = "{{ colors.on_surface_variant.dark.hex }}",
	primary = "{{ colors.primary.dark.hex }}",
	on_primary = "{{ colors.on_primary.dark.hex }}",
	primary_container = "{{ colors.primary_container.dark.hex }}",
	on_primary_container = "{{ colors.on_primary_container.dark.hex }}",
	secondary = "{{ colors.secondary.dark.hex }}",
	secondary_container = "{{ colors.secondary_container.dark.hex }}",
	on_secondary_container = "{{ colors.on_secondary_container.dark.hex }}",
	tertiary = "{{ colors.tertiary.dark.hex }}",
	on_tertiary = "{{ colors.on_tertiary.dark.hex }}",
	tertiary_container = "{{ colors.tertiary_container.dark.hex }}",
	on_tertiary_container = "{{ colors.on_tertiary_container.dark.hex }}",
	error = "{{ colors.error.dark.hex }}",
	error_container = "{{ colors.error_container.dark.hex }}",
	on_error_container = "{{ colors.on_error_container.dark.hex }}",
	outline = "{{ colors.outline.dark.hex }}",
	outline_variant = "{{ colors.outline_variant.dark.hex }}",
	green = "{{ colors.primary.dark.hex }}",
	yellow = "{{ colors.tertiary.dark.hex }}",
	term = {
		"{{ colors.surface.dark.hex }}",
		"{{ colors.error.dark.hex }}",
		"{{ colors.primary.dark.hex }}",
		"{{ colors.tertiary.dark.hex }}",
		"{{ colors.secondary.dark.hex }}",
		"{{ colors.inverse_primary.dark.hex }}",
		"{{ colors.on_tertiary_container.dark.hex }}",
		"{{ colors.on_surface.dark.hex }}",
		"{{ colors.on_surface_variant.dark.hex }}",
		"{{ colors.error_container.dark.hex }}",
		"{{ colors.primary_container.dark.hex }}",
		"{{ colors.tertiary_container.dark.hex }}",
		"{{ colors.secondary_container.dark.hex }}",
		"{{ colors.on_primary_container.dark.hex }}",
		"{{ colors.on_tertiary.dark.hex }}",
		"{{ colors.surface_bright.dark.hex }}",
	},
}

local light = {
	bg = "{{ colors.background.light.hex }}",
	bg_dim = "{{ colors.surface_dim.light.hex }}",
	surface = "{{ colors.surface.light.hex }}",
	container = "{{ colors.surface_container.light.hex }}",
	container_high = "{{ colors.surface_container_high.light.hex }}",
	container_highest = "{{ colors.surface_container_highest.light.hex }}",
	fg = "{{ colors.on_surface.light.hex }}",
	fg_muted = "{{ colors.on_surface_variant.light.hex }}",
	primary = "{{ colors.primary.light.hex }}",
	on_primary = "{{ colors.on_primary.light.hex }}",
	primary_container = "{{ colors.primary_container.light.hex }}",
	on_primary_container = "{{ colors.on_primary_container.light.hex }}",
	secondary = "{{ colors.secondary.light.hex }}",
	secondary_container = "{{ colors.secondary_container.light.hex }}",
	on_secondary_container = "{{ colors.on_secondary_container.light.hex }}",
	tertiary = "{{ colors.tertiary.light.hex }}",
	on_tertiary = "{{ colors.on_tertiary.light.hex }}",
	tertiary_container = "{{ colors.tertiary_container.light.hex }}",
	on_tertiary_container = "{{ colors.on_tertiary_container.light.hex }}",
	error = "{{ colors.error.light.hex }}",
	error_container = "{{ colors.error_container.light.hex }}",
	on_error_container = "{{ colors.on_error_container.light.hex }}",
	outline = "{{ colors.outline.light.hex }}",
	outline_variant = "{{ colors.outline_variant.light.hex }}",
	green = "{{ colors.primary.light.hex }}",
	yellow = "{{ colors.tertiary.light.hex }}",
	term = {
		"{{ colors.surface.light.hex }}",
		"{{ colors.error.light.hex }}",
		"{{ colors.primary.light.hex }}",
		"{{ colors.tertiary.light.hex }}",
		"{{ colors.secondary.light.hex }}",
		"{{ colors.inverse_primary.light.hex }}",
		"{{ colors.on_tertiary_container.light.hex }}",
		"{{ colors.on_surface.light.hex }}",
		"{{ colors.on_surface_variant.light.hex }}",
		"{{ colors.error_container.light.hex }}",
		"{{ colors.primary_container.light.hex }}",
		"{{ colors.tertiary_container.light.hex }}",
		"{{ colors.secondary_container.light.hex }}",
		"{{ colors.on_primary_container.light.hex }}",
		"{{ colors.on_tertiary.light.hex }}",
		"{{ colors.surface_bright.light.hex }}",
	},
}

return vim.o.background == "light" and light or dark
